services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:1.123.9
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    networks:
      - n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8nâ€š
networks:
  n8n:

volumes:
  n8n_data: